# Makefile for memory management package and related test programs
# group id: q
# members: Stefan Behr, Joshua Andersen
# project: HW 6, part 1

CC = gcc
CFLAGS = -Wall -g

PROG = bench
OBJS = freemem.o getmem.o get_mem_stats.o print_heap.o

# source files include bench.c and all files in OBJS except with .o replaced with .c
SRCS = bench.c $(OBJS:.o=.c)
HDRS = mem.h mem_impl.h

# source files containing tests from getmem, freemem, and both together
TEST_SRCS = test_get.c test_free.c test_integration.c
TEST_EXECS = $(TEST_SRCS:.c=)

# for use with the dist and part1 targets used to make tar archives for turn-in
TARNAME = hw6.tar
TARFLAGS = -cvzf

# default target, creates the bench executable
$(PROG): $(PROG).c $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

# any object file is a target, depends on its corresponding C source file,
# as well as both header files. command line omitted to allow default build rule of
# $(CC) $(CFLAGS) -c source-file.c
%.o: %.c $(HDRS)

# test target, recompiles bench executable if necessary, runs bench with default parameters
test: bench
	bench

# target for making executables for all test files (test_free.c, test_get.c, and test_integration.c)
all_tests:
	make test_integration
	make test_free
	make test_get

# target compiling integrated freemem and getmem tests
test_integration: test_integration.c $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

# target for compiling tests for getmem
test_get:  test_get.c getmem.o
	$(CC) $(CFLAGS) -o $@ $^

# target for compiling tests for freemem
test_free: test_free.c freemem.o
	$(CC) $(CFLAGS) -o $@ $^

# remove emacs backup files, executables, object files related to
# the project, and any other project-related cruft, leaving 
# anything else in the directory intact.
# (*.dSYM directories are generated by make under OS X for some reason)
clean:
	rm -rf *~ $(OBJS) bench *.dSYM svn.log $(TARNAME)
	rm -f $(TEST_EXECS)

# create tar archive named hw6.tar for project turn-in, including headers, source files, 
# Makefile, svn.log, and README (along with unit tests in unit_tests.c)
dist:
	rm -f $(TARNAME)
	svn log >svn.log
	tar $(TARFLAGS) $(TARNAME) $(HDRS) $(SRCS) $(TEST_SRCS) Makefile svn.log README