# Makefile for memory management package and related test programs
# group id: q
# members: Stefan Behr, Joshua Andersen
# project: HW 6, part 1

CC = gcc
CFLAGS = -Wall -g

PROG = bench
OBJS = freemem.o getmem.o get_mem_stats.o print_heap.o

# source files include bench.c and all files in OBJS except with .o replaced with .c
SRCS = bench.c $(OBJS:.o=.c)
HDRS = mem.h mem_impl.h

# for use with the dist and part1 targets used to make tar archives for turn-in
TARNAME = hw6.tar
TARFLAGS = -cvzf

# default target, creates the bench executable
$(PROG): $(PROG).c $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

# any object file is a target, depends on its corresponding C source file,
# as well as both header files. command line omitted to allow default build rule of
# $(CC) $(CFLAGS) -c source-file.c
%.o: %.c $(HDRS)

# test target, recompiles bench executable if necessary, runs bench with default parameters
test: bench
	bench

# create tar archive named hw6.tar for project turn-in, including headers, source, Makefile, svn.log, README
dist:
	rm -f $(TARNAME)
	svn log >svn.log
	tar $(TARFLAGS) $(TARNAME) $(HDRS) $(SRCS) Makefile svn.log README

# getmem program for development purposes, to be removed later, do not use
getdev:  getdev.c $(HDRS)
	$(CC) $(CFLAGS) getdev.c getmem.c -o getdev

# cleans up getmemdev, to be removed later
cleanget:
	rm getdev

# freemem testing program
freedev: freedev.c $(HDRS)
	$(CC) $(CFLAGS) -o $@ $< freemem.c

# cleans up freedev (freemem testing program)
cleanfree:
	rm -rf freedev freedev.dSYM

# remove emacs backup files, executables, object files related to
# the project, and any other project-related cruft, leaving 
# anything else in the directory intact.
# (*.dSYM directories are generated by make under OS X for some reason)
clean:
	rm -rf *~ $(OBJS) bench *.dSYM svn.log $(TARNAME)